# Generated by Django 2.0.2 on 2018-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_setup_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('source', models.URLField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('Editor', 'Editor'), ('Member', 'Member')], default='Member', max_length=16),
        ),
    ]
