# Generated by Django 2.0.2 on 2018-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180515_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='label',
            field=models.CharField(default='Sports', max_length=64),
            preserve_default=False,
        ),
    ]
