# Generated by Django 2.0.2 on 2018-05-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_newssource_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.NewsSource'),
        ),
    ]
