# Generated by Django 2.0.2 on 2018-05-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20180516_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='new',
            new_name='news',
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Discarded', 'Discarded'), ('Sent', 'Sent'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='setup',
            name='max_review_time_editor',
            field=models.IntegerField(help_text='Maximum time in minutes before news is sent out/discarded', verbose_name='Max review-time (Editor)'),
        ),
    ]
