# Generated by Django 2.0.2 on 2018-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20180516_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('news', 'accepted')},
        ),
        migrations.AddField(
            model_name='result',
            name='read',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='participation_threshold_editor',
            field=models.IntegerField(default=75, help_text="Min % of participating editors before the participants' votes are considered", verbose_name='Participation threshold (Editor)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='participation_threshold_user',
            field=models.IntegerField(default=75, help_text="Min % of participating users before the participants' votes are considered", verbose_name='Participation threshold (User)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='accepted',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('news', 'member')},
        ),
    ]
