# Generated by Django 2.0.2 on 2018-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20180516_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='latest',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Discarded', 'Discarded'), ('Sent', 'Sent'), ('Cancelled', 'Cancelled'), ('Scored', 'Scored'), ('Not Scored', 'Not Scored')], default='Pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='result',
            name='read',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='review_threshold_editor',
            field=models.IntegerField(help_text='Min +ve % review (based on total votes) before news is sent out/trashed', verbose_name='Review threshold (Editor)'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='review_threshold_user',
            field=models.IntegerField(help_text='Min +ve % review (based on total votes) before editor is scored +ve/-ve', verbose_name='Review threshold (User)'),
        ),
    ]
